CMSys project/WebClient/Areas/Admin/Controllers/AdminTrainerGroupController.cs
using System;
using System.Collections.Generic;
using AutoMapper;
using BLL.Contract;
using CMSys_project.ViewModels;
using Domain.Entities.UserEntities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys_project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/TrainerGroup")]
    [Authorize(Roles = "Administrator")]
    public class AdminTrainerGroupController : Controller
    {
        private readonly ICatalogService _iCatalogService;
        private readonly IMapper _iMapper;

        public AdminTrainerGroupController(ICatalogService iCatalogService, IMapper iMapper)
        {
            _iCatalogService = iCatalogService;
            _iMapper = iMapper;
        }

        [Route("Info")]
        public IActionResult Info()
        {
            IEnumerable<TrainerGroupVM> trainerGroupVMs =
               _iMapper.Map<IEnumerable<TrainerGroup>, IEnumerable<TrainerGroupVM>>(_iCatalogService.GetAllTrainerGroup());
            return View("Info", trainerGroupVMs);
        }

        [Route("Create")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Route("Create")]
        [HttpPost]
        public IActionResult Create(TrainerGroupVM trainerGroup)
        {
            if (!ModelState.IsValid)
            {
                return View(trainerGroup);
            }
            trainerGroup.Id = Guid.NewGuid();
            TrainerGroup trainerGr = _iMapper.Map<TrainerGroupVM, TrainerGroup>(trainerGroup);
            try
            {
                _iCatalogService.AddTrainerGroup(trainerGr);
                return RedirectToAction("Info");

            }
            catch
            {

                ViewBag.Role = "Admin";
                ViewBag.Message = $"Trainer Group with name {trainerGr.Name} is already existed";
                return View("Error");
            }

        }

        [Route("Edit/{id}")]
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            TrainerGroup trainerGroup = _iCatalogService.GetTrainerGroup(id);
            TrainerGroupVM trainerGr = _iMapper.Map<TrainerGroup, TrainerGroupVM>(trainerGroup);
            if (trainerGroup != null)
            {
                return View(trainerGr);
            }

            ViewBag.Role = "Admin";
            ViewBag.Message = "Trainer Group was not found";
            return View("Error");
        }

        [Route("Edit/{id}")]
        [HttpPost]
        public IActionResult Edit(TrainerGroupVM trainerGroup)
        {
            if (!ModelState.IsValid)
            {
                return View(trainerGroup);
            }
            TrainerGroup trainerGr = _iMapper.Map<TrainerGroupVM, TrainerGroup>(trainerGroup);
            try
            {
                _iCatalogService.EditTrainerGroup(trainerGr);
                return RedirectToAction("Info");
            }
            catch
            {
                ViewBag.Role = "Admin";
                ViewBag.Message = $"Course Group with name {trainerGr.Name} is already existed";
                return View("Error");
            }
        }

        [Route("Delete/{id}")]
        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(Guid id)
        {
            {
                TrainerGroup trainerGroup = _iCatalogService.GetTrainerGroup(id);
                TrainerGroupVM trainerGroupVm = _iMapper.Map<TrainerGroup, TrainerGroupVM>(trainerGroup);

                if (trainerGroupVm != null)
                {
                    int countTrainers = trainerGroup.Trainer.Count;
                    if (countTrainers != 0)
                    {
                        ViewBag.Role = "Admin";
                        ViewBag.Message = $"Course group has dependents and cannot be deleted:  Course: {countTrainers}";
                        return View("Error");
                    }
                    return View(trainerGroupVm);
                }
            }

            ViewBag.Role = "Admin";
            ViewBag.Message = "Trainer group was not found";
            return View("Error");
        }

        [Route("Delete/{id}")]
        [HttpPost]
        public IActionResult Delete(Guid id)
        {

            TrainerGroup trainerGroup = _iCatalogService.GetTrainerGroup(id);
            if (trainerGroup != null && trainerGroup.Trainer.Count == 0)
            {
                _iCatalogService.DeleteTrainerGroup(trainerGroup.Id);
                return RedirectToAction("Info");
            }

            ViewBag.Role = "Admin";
            ViewBag.Message = "Trainer group was not found";
            return View("Error");
        }

        [Route("Error")]
        public IActionResult Error()
        {
            return View("Error");
        }
    }
}

CMSys project/WebClient/Areas/Admin/Views/AdminTrainerGroup/Create.cshtml
@model CMSys_project.ViewModels.TrainerGroupVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewBag.Title = "Add Trainer group";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Main{
    <form asp-action="Create" asp-controller="AdminTrainerGroup">
        <div class="form-group">
            <label asp-for="Name" class="control-label">Name</label>
            <input type="text" asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-success"/>
        </div>
    </form>
}

@section validation {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

CMSys project/WebClient/Areas/Admin/Views/AdminTrainerGroup/Delete.cshtml
@model CMSys_project.ViewModels.TrainerGroupVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Delete Trainer group";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Main
{
    <div>
        <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

        </dl>

        <div>
            <div class="alert alert-warning" role="alert">
                Delete this course group?
            </div>
            <div>
                <form style="display: inline-block" asp-controller="AdminTrainerGroup" asp-action="Delete" method="post">
                    <button type="submit" class="btn btn-primary">Yes</button>
                </form>
                <form style="display: inline-block" asp-controller="AdminTrainerGroup" asp-action="Info" method="post">
                    <button type="submit" class="btn btn-primary">No</button>
                </form>
            </div>
        </div>
    </div>
}

CMSys project/WebClient/Areas/Admin/Views/AdminTrainerGroup/Edit.cshtml
@model CMSys_project.ViewModels.TrainerGroupVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


@{
    ViewBag.Title = "Edit Trainer Group";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Main{
    <form asp-action="edit" asp-controller="AdminTrainerGroup" asp-route-id="@Model.Id">
        <div class="form-group">
            <label asp-for="Name" class="control-label">Name</label>
            <input type="text" asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-outline-primary"/>
        </div>
    </form>
}

@section validation {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

CMSys project/WebClient/Areas/Admin/Views/AdminTrainerGroup/Info.cshtml
@using CMSys_project.ViewModels
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewBag.Title = "Trainer Groups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Main{
    <h2>Trainer groups</h2>
    <div class="form-group">
        <a class="btn btn-sm btn-primary" asp-action="Create">Add group</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Name</th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        @foreach (TrainerGroupVM item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>
                    <a class="btn btn-sm btn-info" asp-action="Edit" asp-controller="AdminTrainerGroup" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-sm btn-danger" asp-action="Delete" asp-controller="AdminTrainerGroup" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
}