CMSys project/WebClient/Areas/User/Controllers/UserTrainerController.cs
using System;
using System.Collections.Generic;
using AutoMapper;
using BLL.Contract;
using CMSys_project.ViewModels;
using Domain.Entities.UserEntities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys_project.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "User, Administrator")]
    [Route("User/Trainer")]
    public class UserTrainerController : Controller
    {
        private readonly ICatalogService _iCatalogService;
        private readonly IMapper _iMapper;

        public UserTrainerController(ICatalogService iCatalogService, IMapper iMapper)
        {
            _iCatalogService = iCatalogService;
            _iMapper = iMapper;
        }

        [Route("Info")]
        public IActionResult Info()
        {
            IEnumerable<TrainerVM> trainerVMs =
                _iMapper.Map<IEnumerable<Trainer>, IEnumerable<TrainerVM>>(_iCatalogService.GetAllTrainer());
           
            return View("Info", trainerVMs);
        }

 
        [Route("Profile/{id}")]
        public IActionResult Profile(Guid id)
        {

            Trainer trainer = _iCatalogService.GetTrainer(id);
            ViewData.Model = _iMapper.Map<Trainer, TrainerVM>(trainer);
            if (trainer is null)
            {
                ViewBag.Message = "Trainer was not found";
                return View("Error");
            }
            return View();

        }
    }
}

CMSys project/WebClient/Areas/User/Views/UserTrainer/Info.cshtml
@using CMSys_project.ViewModels
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewBag.Title = "Trainers";
    if(User.IsInRole("Administrator"))
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    if(User.IsInRole("User"))
    {
        Layout = "~/Views/Shared/_UserLayout.cshtml";
    }
}
@section Main{
    <h2>Trainers</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Group</th>
                <th>Photo</th>
                <th>Name</th>
                <th>About</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (TrainerVM item in Model)
        {
            <tr>
                <td>@item.Group.Name</td>
                <td> @{
                         if (item.User.Photo.Length == 0)
                         {
                             <text>No photo</text>
                         }
                         else
                         {
                             <img style="display: inline-block; width: 190px; height: 256px"
                                  src="data:image;base64,@Convert.ToBase64String(item.User.Photo)" alt="User image" />
                         }
                     }</td>
                <td>@item.User.FullName</td>
                <td>@item.About</td>
                <td>
                    <a class="btn btn-sm btn-info" asp-action="Profile" asp-controller="UserTrainer" asp-route-id="@item.UserId">Info</a>

                </td>
            </tr>
        }
        </tbody>
    </table>
}

CMSys project/WebClient/Areas/User/Views/UserTrainer/Profile.cshtml
@model CMSys_project.ViewModels.TrainerVM;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewBag.Title = "Trainer info";
    if(User.IsInRole("Administrator"))
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    if(User.IsInRole("User"))
    {
        Layout = "~/Views/Shared/_UserLayout.cshtml";
    }
}

@section Main{
    <h2>Trainer info</h2>
    <div class="form-group">
    </div>
    <thead>
    </thead>
    <body>
        <h2> @{
                 if (Model.User.Photo.Length == 0)
                 {
                     <text>No photo</text>
                 }
                 else
                 {
                     <img style="display: inline-block; width: 190px; height: 256px"
                          src="data:image;base64,@Convert.ToBase64String(Model.User.Photo)" alt="User image" />
                 }
             } @Model.User.FullName</h2>
        <br />


        <h5>Description</h5>
        <p>
            @Model.About
        </p>
        <a class="btn btn-info" asp-action="Info" asp-controller="UserTrainer">Back</a>
    </body>

}a