CMSys project/WebClient/Areas/Admin/Controllers/AdminCourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using BLL.Contract;
using CMSys_project.ViewModels;
using Domain.Entities.CourseEntities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CMSys_project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/Course")]
    [Authorize(Roles = "Administrator")]
    public class AdminCourseController : Controller
    {
        private readonly ICatalogService _iCatalogService;
        private readonly IMapper _iMapper;

        public AdminCourseController(ICatalogService iCatalogService,
            IMapper iMapper)
        {
            _iCatalogService = iCatalogService;
            _iMapper = iMapper;
        }

        [Route("Info")]
        public IActionResult Info()
        {
            IEnumerable<CourseVM> courseGroupVms =
                _iMapper.Map<IEnumerable<Course>, IEnumerable<CourseVM>>(_iCatalogService.GetAllCourse());
            return View("Info", courseGroupVms);
        }

        [Route("Create")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewData.Model = new CourseVM
            {
                CourseGroups = new SelectList(_iCatalogService.GetAllCourseGroup(), "Id", "Name"),
                Trainers = new List<TrainerVM>(),
                CourseGroup = null
            };

            return View();
        }

        [Route("Create")]
        [HttpPost]
        public IActionResult Create(CourseVM course)
        {
            if (!ModelState.IsValid)
            {
                course.CourseGroups = new SelectList(_iCatalogService.GetAllCourseGroup(), "Id", "Name");
                return View(course);
            }

            course.Id = Guid.NewGuid();
            Course courseGr = _iMapper.Map<CourseVM, Course>(course);

            try
            {
                _iCatalogService.AddCourse(courseGr);
                return RedirectToAction("Info");
            }
            catch
            {
                ViewBag.Message = "Something goes wrong!";
                return View("Error");
            }
        }

        [Route("Edit/{id}")]
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            Course course = _iCatalogService.GetCourse(id);
            CourseVM courseVm;
            try
            {
                courseVm = _iMapper.Map<Course, CourseVM>(course);
                courseVm.CourseGroups = new SelectList(
                    _iCatalogService.GetAllCourseGroup().Select(t => new {t.Id, t.Name}),
                    "Id", "Name");
                ViewData.Model = courseVm;
            }
            catch
            {
                ViewBag.Message = "Course was not found";
                return View("Error");
            }

            return View(courseVm);
        }

        [Route("Edit/{id}")]
        [HttpPost]
        public IActionResult Edit(CourseVM courseVm)
        {
            if (!ModelState.IsValid)
            {
                courseVm.CourseGroups = new SelectList(
                    _iCatalogService.GetAllCourseGroup().Select(t => new {t.Id, t.Name}),
                    "Id", "Name");
                return View(courseVm);
            }

            try
            {
                Course course = _iMapper.Map<CourseVM, Course>(courseVm);
                _iCatalogService.EditCourse(course);
                return RedirectToAction("Info");
            }
            catch
            {
                ViewBag.Message = "Course was not found";
                return View("Error");
            }
        }

        [Route("Delete/{id}")]
        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(Guid id)
        {
            {
                Course course = _iCatalogService.GetCourse(id);
                CourseVM courseVm = _iMapper.Map<Course, CourseVM>(course);

                if (courseVm != null)
                {
                    int countCourses = course.TrainerCourse.Count;
                    if (countCourses != 0)
                    {
                        ViewBag.Message = $"Course has dependents and cannot be deleted:  Course: {countCourses}";
                        return View("Error");
                    }

                    return View(courseVm);
                }
            }

            ViewBag.Message = "Course was not found";
            return View("Error");
        }

        [Route("Delete/{id}")]
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            {
                Course course = _iCatalogService.GetCourse(id);
                if (course != null && course.TrainerCourse.Count == 0)
                {
                    _iCatalogService.DeleteCourse(course.Id);
                    return RedirectToAction("Info");
                }
            }

            ViewBag.Message = "Course was not found";
            return View("Error");
        }

        [Route("Error")]
        public IActionResult Error()
        {
            return View("Error");
        }

        [Route("EditTrainer/{id}")]
        [HttpGet]
        public IActionResult EditTrainer(Guid id)
        {
            Course course = _iCatalogService.GetCourse(id);
            try
            {
                CourseVM courseVm = _iMapper.Map<Course, CourseVM>(course);

                courseVm.AllTheTrainers = new SelectList(_iCatalogService.GetAllTrainer()
                    .Except(_iCatalogService.GetCourseTrainers(course))
                    .Select(t => new {Id = t.UserId, FullName = $"{t.User.Name} {t.User.Surname}"}), "Id", "FullName");
                ViewData.Model = courseVm;
            }

            catch (Exception)
            {
                ViewBag.Message = "Course was not found";
                return View("Error");
            }

            if (course != null)
            {
                return View();
            }

            ViewBag.Message = "Course was not found";
            return View("Error");
        }


        [Route("EditTrainer/DeleteTrainer")]
        public IActionResult DeleteTrainer(Guid courseId, Guid trainerId)
        {
            _iCatalogService.DeleteCourseTrainer(_iCatalogService.GetCourse(courseId),
                _iCatalogService.GetTrainer(trainerId));
            return RedirectToAction("EditTrainer", new {id = courseId});
        }

        [Route("EditTrainer/AddTrainer")]
        public IActionResult AddTrainer(Guid courseId, CourseVM course)
        {
            course.Id = courseId;
            _iCatalogService.AddTrainerCourse(_iCatalogService.GetCourse(course.Id),
                _iCatalogService.GetTrainer(course.SelectedTrainer));
            return RedirectToAction("EditTrainer", new {id = course.Id});
        }

        [Route("Profile/{id}")]
        public IActionResult Profile(Guid id)
        {
            Course course = _iCatalogService.GetCourse(id);
            ViewData.Model = _iMapper.Map<Course, CourseVM>(course);
            if (course is null)
            {
                ViewBag.Message = "Course was not found";
                return View("Error");
            }

            return View();
        }
    }
}

CMSys project/WebClient/Areas/User/Controllers/UserCourseController.cs
using System;
using System.Collections.Generic;
using AutoMapper;
using BLL.Contract;
using CMSys_project.ViewModels;
using Domain.Entities.CourseEntities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys_project.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "User, Administrator")]
    [Route("")]
    [Route("User/Course")]
    public class UserCourseController : Controller
    {
        private readonly ICatalogService _iCatalogService;
        private readonly IMapper _iMapper;

        public UserCourseController(ICatalogService iCatalogService, IMapper iMapper)
        {
            _iCatalogService = iCatalogService;
            _iMapper = iMapper;
        }
        [Route("")]
        [Route("Info")]
        public IActionResult Info()
        {
            IEnumerable<CourseVM> courseGroupVms =
                _iMapper.Map<IEnumerable<Course>, IEnumerable<CourseVM>>(_iCatalogService.GetAllCourse());
            return View("Info", courseGroupVms);

        }

        [Route("Error")]
        public IActionResult Error()
        {
            return View("Error");
        }

        [Route("Profile/{id}")]
        public IActionResult Profile(Guid id)
        {

            Course course = _iCatalogService.GetCourse(id);
            ViewData.Model = _iMapper.Map<Course, CourseVM>(course);
            if (course is null)
            {
                ViewBag.Message = "Course was not found";
                return View("Error");
            }

            return View();
        }

    }
}

CMSys project/WebClient/Areas/Admin/Views/AdminCourse/Create.cshtml
@using CMSys_project.ViewModels
@model CMSys_project.ViewModels.CourseVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Add Course";
}

@section Main{
    <form asp-action="Create" asp-controller="UserCourse">
        <div class="form-group">
            <label asp-for="Name" class="control-label">Name</label>
            <input type="text" asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <label>New course</label>
            <div class="form-group">
                <input type="checkbox" asp-for="Status"/>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type"></label>
            <div class="form-group">
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<CourseTypeVM>()">
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Schedule"></label>
            <div class="form-group">
                <select asp-for="Schedule" asp-items="Html.GetEnumSelectList<WayPlanningVM>()">
                </select>
                <span asp-validation-for="Schedule" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label>Course group</label>
            <select class="form-control" asp-for="GroupCourseId" asp-items="@Model.CourseGroups"></select>
            <span asp-validation-for="GroupCourseId"></span>
        </div>
        <div class="form-group">
            <label>Description</label>
            <div class="form-group">
                <input type="text" asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description"></span>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-success"/>
        </div>
    </form>
}

@section validation {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

CMSys project/WebClient/Areas/Admin/Views/AdminCourse/Delete.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model CMSys_project.ViewModels.CourseVM
@{
    ViewData["Title"] = "Delete Course";
}

@section Main
{
    <div>
        <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

        </dl>

        <div>
            <div class="alert alert-warning" role="alert">
                Delete this course?
            </div>
            <div>
                <form style="display: inline-block" asp-controller="AdminCourse" asp-action="Delete" method="post">
                    <button type="submit" class="btn btn-primary">Yes</button>
                </form>
                <form style="display: inline-block" asp-controller="AdminCourse" asp-action="Info" method="post">
                    <button type="submit" class="btn btn-primary">No</button>
                </form>
            </div>
        </div>
    </div>
}

CMSys project/WebClient/Areas/Admin/Views/AdminCourse/Edit.cshtml
@using CMSys_project.ViewModels
@model CMSys_project.ViewModels.CourseVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.Title = "Edit Course";
}

@section Main{
    <form asp-action="edit" asp-controller="AdminCourse" asp-route-id="@Model.Id">
        <div class="form-group">
            <label>Name</label>
            <div class="form-group">
                <input type="text" asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group">
            <label>New course</label>
            <div class="form-group">
                <input type="checkbox" asp-for="Status"/>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Type"></label>
            <div class="form-group">
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<CourseTypeVM>()">
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Schedule"></label>
            <div class="form-group">
                <select asp-for="Schedule" asp-items="Html.GetEnumSelectList<WayPlanningVM>()">
                </select>
                <span asp-validation-for="Schedule" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label>Course group</label>
            <select class="form-control" asp-for="GroupCourseId" asp-items="@Model.CourseGroups"></select>
        </div>
        <div class="form-group">
            <label>Description</label>
            <div class="form-group">
                <input type="text" asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description"></span>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Send" class="btn btn-outline-primary"/>
        </div>
    </form>
}

@section validation {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

CMSys project/WebClient/Areas/Admin/Views/AdminCourse/EditTrainer.cshtml
@using CMSys_project.ViewModels
@model CMSys_project.ViewModels.CourseVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Edit trainers";
}

@section Main{
    <h2>@Model.Name</h2>
    <hr/>

    <table class="table table-bordered">
        <tr>
            <td>Profile</td>
            <td>Action</td>
        </tr>
        @{
            foreach (TrainerVM trainer in Model.Trainers)
            {
                <tr>
                    <td>
                        @trainer.User.FullName
                    </td>
                    <td>
                        <a asp-controller="AdminCourse" asp-action="DeleteTrainer"
                           asp-route-courseId="@Model.Id" asp-route-trainerId="@trainer.UserId">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        }
    </table>
    <br/>

    <form asp-controller="AdminCourse" asp-action="AddTrainer" asp-route-courseId="@Model.Id" method="post">
        <div class="form-group">
            <label>Select trainer:</label>
            <select class="form-control" asp-for="SelectedTrainer" asp-items="@Model.AllTheTrainers"></select>
        </div>

        <input class="btn btn-primary" type="submit" value="Add"/>
    </form>

    <br/>
    <a class="btn btn-info" asp-controller="AdminCourse" asp-action="Info" asp-route-id="@Model.Id">Back</a>
}

@section validation {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

CMSys project/WebClient/Areas/Admin/Views/AdminCourse/Info.cshtml
@using CMSys_project.ViewModels
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Courses";
}

@section Main{
    <h2>Courses</h2>
    <div class="form-group">
        <a class="btn btn-sm btn-primary" asp-action="Create">Add course</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Name</th>
            <th>Course Group</th>
            <th>Type</th>
            <th>Schedule</th>
            <th>Status</th>
            <th>Trainers</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach (CourseVM item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.CourseGroup.Name</td>
                <td>@item.Type</td>
                <td>@item.Schedule</td>
                <td>
                    @{
                        if (item.Status)
                        {
                            <text>New</text>
                        }
                    }
                </td>

                <td>
                    @foreach (TrainerVM trainer in item.Trainers)
                    {
                        <li>
                            @trainer.User.FullName
                        </li>
                    }
                </td>

                <td>
                    <a class="btn btn-sm btn-info" asp-action="Edit" asp-controller="AdminCourse" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-sm btn-danger" asp-action="Delete" asp-controller="AdminCourse" asp-route-id="@item.Id">Delete</a>
                    <a class="btn btn-sm btn-warning" asp-action="EditTrainer" asp-controller="AdminCourse" asp-route-id="@item.Id">EditTrainers</a>
                    <a class="btn btn-sm btn-info" asp-action="Profile" asp-controller="AdminCourse" asp-route-id="@item.Id">Info</a>
                </td>
            </tr>
            <td colspan="7">
                @item.Description
            </td>
        }
        </tbody>
    </table>
}

CMSys project/WebClient/Areas/Admin/Views/AdminCourse/Profile.cshtml
@using CMSys_project.ViewModels
@model CMSys_project.ViewModels.CourseVM;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Courses";
}

@section Main{
    <h2>Courses</h2>
    <div class="form-group">
    </div>
    <thead>
    </thead>
    <body>
    <h2>@Model.Name</h2>
    <br/>
    <h4>Trainers</h4>
    @foreach (TrainerVM trainer in Model.Trainers)
    {
        <li>
            @trainer.User.FullName
        </li>
    }
    <br/>

    <h6>Type: @Model.Type</h6>
    <h6>Arrangement: @Model.Schedule</h6>
    <br/>

    <h5>Description</h5>
    <p>
        @Model.Description
    </p>
    <a class="btn btn-info" asp-action="Info" asp-controller="AdminCourse">Back</a>
    </body>

}